---
documentclass: article
classoption:
 - a4paper
 - titlepage
title: Les accélérateurs matériels
author:
  - Antoine Greget
  - Quentin Gliech
date: \today
toc: true
lang: fr
urlcolor: cyan
bibliography: sources.bib
biblio-style: unsrt
header-includes:
  - \usepackage[nottoc]{tocbibind}
---
